# Generated by Django 5.2 on 2025-05-08 09:47

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_column="title", max_length=200, verbose_name="Заголовок"
                    ),
                ),
                ("text", models.TextField(max_length=5000, verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        upload_to="static/blog_previews/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_default=False, verbose_name="Признак публикации"
                    ),
                ),
                (
                    "congratulations_sent",
                    models.BooleanField(
                        db_default=False, verbose_name="Уже поздравили"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        db_default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись в блоге",
                "verbose_name_plural": "Записи в блоге",
                "db_table": "blog_records",
                "ordering": ["title"],
            },
        ),
    ]
