# Generated by Django 5.2 on 2025-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogrecord_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogrecord",
            name="preview",
            field=models.ImageField(
                blank=True,
                upload_to="static/blog_previews/",
                verbose_name="Изображение",
            ),
        ),
    ]
