# Generated by Django 5.2 on 2025-05-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogrecord_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogrecord",
            name="congratulations_sent",
            field=models.BooleanField(db_default=False, verbose_name="Уже поздравили"),
        ),
    ]
