# Generated by Django 5.2 on 2025-05-08 09:47

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name", max_length=150, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="description",
                        max_length=500,
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "db_table": "category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContactsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_column="email",
                        max_length=254,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        db_column="telegram", max_length=150, verbose_name="Телеграм"
                    ),
                ),
                (
                    "vk_group",
                    models.URLField(
                        db_column="vkgroup",
                        max_length=150,
                        verbose_name="Группа ВКонтакте",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_column="updated_at",
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Дата последнего изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
                "db_table": "contacts",
                "ordering": ["updated_at", "email", "telegram"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Ваше имя")),
                (
                    "email",
                    models.EmailField(
                        db_column="email",
                        max_length=254,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "message",
                    models.TextField(max_length=5000, verbose_name="Сообщение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение пользователя",
                "verbose_name_plural": "Сообщения пользователей",
                "db_table": "feedback",
                "ordering": ["name", "created_at", "email"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name", max_length=150, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        db_column="description",
                        max_length=500,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        db_column="image",
                        upload_to="static/images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        db_column="price", default=0.0, verbose_name="Цена за покупку"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="created_at",
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_column="updated_at",
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Дата последнего изменения",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "db_table": "product",
                "ordering": ["name"],
            },
        ),
    ]
