# Generated by Django 5.2 on 2025-04-21 11:59

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_column="email",
                        max_length=254,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        db_column="telegram", max_length=150, verbose_name="Телеграм"
                    ),
                ),
                (
                    "vk_group",
                    models.URLField(
                        db_column="vkgroup",
                        max_length=150,
                        verbose_name="Группа ВКонтакте",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_column="updated_at",
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Дата последнего изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
                "db_table": "contacts",
                "ordering": ["updated_at", "email", "telegram"],
            },
        ),
    ]
