# Generated by Django 5.2 on 2025-04-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contactsinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                db_column="image",
                upload_to="images/",
                verbose_name="Изображение",
            ),
        ),
    ]
