# Generated by Django 5.2 on 2025-05-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                db_default=False, verbose_name="Признак публикации"
            ),
        ),
    ]
