# Generated by Django 5.2 on 2025-04-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(
                blank=True, db_column="image", verbose_name="Изображение"
            ),
        ),
    ]
