# Generated by Django 5.2 on 2025-04-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                db_column="image",
                upload_to="static/images/",
                verbose_name="Изображение",
            ),
        ),
    ]
