# Generated by Django 5.2 on 2025-04-30 11:57

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Ваше имя")),
                (
                    "email",
                    models.EmailField(
                        db_column="email",
                        max_length=254,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "message",
                    models.TextField(max_length=5000, verbose_name="Сообщение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение пользователя",
                "verbose_name_plural": "Сообщения пользователей",
                "db_table": "feedback",
                "ordering": ["name", "created_at", "email"],
            },
        ),
    ]
