# Generated by Django 5.2 on 2025-05-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                db_column="description",
                max_length=2000,
                verbose_name="Описание",
            ),
        ),
    ]
